[package]
name = "flasher-gui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Native PocketCHIP recovery and simulation wizard"
publish = false

[dependencies]
flasher-core.workspace = true
eframe.workspace = true
tempfile.workspace = true

[lints]
workspace = true
