[package]
name = "flasher-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
description = "PocketCHIP recovery diagnostics and simulation CLI"
publish = false

[dependencies]
flasher-core.workspace = true
ctrlc.workspace = true

[lints]
workspace = true
